### PR TITLE
Test master

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by wsmoses** [comment]
we realized we we'rent throwing errors for llvm insert instructions that were runtime active [aka storing, via an insert instruction, a contant pointer, into a differentiable data structure]

**Comment by ChrisRackauckas** [comment]
So it should've errored before and it just didn't? 😅

**Comment by ChrisRackauckas** [comment]
I guess like the others, LinearProblem might need to be mutable?

**Comment by ChrisRackauckas** [comment]
Bump, the question is:

> I guess like the others, LinearProblem might need to be mutable?

**Comment by wsmoses** [comment]
@ChrisRackauckas can you mark https://github.com/SciML/LinearSolve.jl/blob/33911f60bda7ecd0eeff2d9f75230e48d47503a8/test/enzyme.jl#L178 as const A

The issue yells that https://github.com/SciML/LinearSolve.jl/blob/33911f60bda7ecd0eeff2d9f75230e48d47503a8/test/enzyme.jl#L187 is type unstable, and uses a constant variable (A) being stored into a differentiable LinearProblem. Marking it as const/type stable may optimize out the linear problem, solving the issue

**Comment by ChrisRackauckas** [comment]
Fixing the type stability and marking things constant didn't seem to effect it.

**Pull request closed without merging**
