### PR TITLE
Patch SimpleGMRES when `b`  is updated

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
@ChrisRackauckas buildkite doesn't seem to be running on PRs

**Comment by ChrisRackauckas** [comment]
It only runs on the main package, not on forks

**Comment by avik-pal** [comment]
@ChrisRackauckas  can you make https://buildkite.com/julialang/linearsolve-dot-jl/builds/1504 public? I am not sure what is failing. It passed locally for me

**Comment by ChrisRackauckas** [comment]
Public.

**Pull request merged**
