### PR TITLE
example blocks

### PR DESCRIPTION
**Pull request by ArnoStrouwen**
Fixes https://github.com/SciML/LinearSolve.jl/issues/186

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Also remember to set strict https://github.com/SciML/DiffEqFlux.jl/blob/master/docs/make.jl#L15-L22

**Comment by ChrisRackauckas** [comment]
oops, accidentally just did it to master. Rebase.

**Comment by ArnoStrouwen** [comment]
For strict fix https://github.com/SciML/LinearSolve.jl/issues/186 first ?

**Comment by ChrisRackauckas** [comment]
yeah, why is `ldiv!` not on `Diagonal`? It's throwing away the operator for some reason and just keeping the array. That's weird.

**Pull request merged**
