### PR TITLE
Add args... and kwargs... for FastFactorizations

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Comment by Wimmerer** [comment]
Oh I suppose I should also be doing that for other solvers like `function SciMLBase.solve(cache::LinearCache, alg::UMFPACKFactorization)`?

**Comment by ChrisRackauckas** [comment]
Can we add `abstol=1e-6` or something to the `solve` call in the tests to catch this?

**Comment by Wimmerer** [comment]
In `check_interface` perhaps?

**Comment by ChrisRackauckas** [comment]
Okay yeah cool, it should be catching this in the tests now.

**Pull request merged**
