### PR TITLE
Make the rrule's outer product lazy

### PR DESCRIPTION
**Pull request by mohamed82008**
## Checklist

- [x] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context

This PR implements the suggestion in https://discourse.julialang.org/t/how-do-you-speed-up-the-linear-sparse-solver-in-zygote/111801/41?u=mohamed82008. To be safe, I also bumped the major version because the output type of `Zygote.gradient` wrt the matrix is changed in this PR. No new documentation was added as this PR is just a performance improvement.

### CODE REVIEW

**Comment by mohamed82008** [comment]
After this PR, the gradient wrt the matrix requires only `O(n)` memory.

```julia
using LinearAlgebra, LinearSolve, Zygote

n = 100; A = rand(n, n); b1 = rand(n); b2 = rand(n);

function invquad(a, A, b)
    prob = LinearProblem(A, b)
    sol = solve(
        prob,
        LinearSolve.DefaultLinearSolver(LinearSolve.DefaultAlgorithmChoice.RFLUFactorization),
    )
    return dot(a, sol.u)
end

db1, dA, db2 = Zygote.gradient(invquad, b1, A, b2);

Base.summarysize(dA)
# 1752

Base.summarysize(A)
# 80040
```

**Comment by mohamed82008** [comment]
Tests seem to pass. I added version 3 to the docs toml file to hopefully fix the docs build.

**Comment by mohamed82008** [comment]
The test failure is new and not related to this PR. I only added a version number in the last commit but the test failure is a method ambiguity failure. If you re-run the tests on master, you will probably get the same failure. Could be a dependency that upgraded and broke things between the 2 commits.

**Comment by ChrisRackauckas** [comment]
It seems like the tolerance is just set too tight in that test and multithreading in BLAS change it at that level.

**Comment by mohamed82008** [comment]
new release?

**Comment by ChrisRackauckas** [comment]
I was going to handle some downgrade and test tolerance stuff https://github.com/SciML/LinearSolve.jl/pull/485 and release in a little bit.

**Comment by ChrisRackauckas** [comment]
Wait, why was this a major?

**Comment by mohamed82008** [comment]
To be safe, I bumped the major version because the output type of Zygote.gradient wrt the matrix is changed in this PR.

**Comment by ChrisRackauckas** [comment]
I don't think we guaranteed the type on the pullback anywhere, just that it has the right actions in the derivative, and the Zygote overload was just added a release ago, so together I don't think this constitute a major bump but instead a minor.

**Comment by mohamed82008** [comment]
Feel free to revert it. I was being safe. I wouldn't want the type to change on me if I am a user.

**Pull request merged**
