### PR TITLE
switch to `SciMLBase`s version of `_unwrap_val`

### PR DESCRIPTION
**Pull request by oscardssmith**
part of the migration in https://github.com/SciML/NonlinearSolve.jl/pull/94 and https://github.com/SciML/OrdinaryDiffEq.jl/pull/1790.

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]

**Comment by devmotion** [comment]
Maybe it would be less breaking to not change the type parameter but only change `_unwrap_val` and the constructor of `OperatorAssumptions` where it is used?

**Comment by YingboMa** [comment]
Ah, yeah, I guess we can always normalize `OperatorAssumptions{nothing}` to `OperatorAssumptions{Nothing}` in construction.

**Comment by oscardssmith** [comment]
Is that better? If so, I can switch it.

**Comment by YingboMa** [comment]
Yeah, then it won't be breaking at all.

**Pull request merged**
