### PR TITLE
Specialize UMFPack initialization

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@Wimmerer could you look into the KLU one? This one might finally finish the https://github.com/SciML/OrdinaryDiffEq.jl/pull/1543 PR.

**Comment by Wimmerer** [comment]
Yes, but why are we constructing the UMFPACK factorization directly? So that we don't immediately run the symbolic?

**Comment by ChrisRackauckas** [comment]
Yes, we just want the initialization of the cache without doing any of the work in order to get the types right.

**Comment by Wimmerer** [comment]
I'll also see if I can make a PR to SuiteSparse.jl, it seems really bad that we should be handling finalizers at this level just to defer factorization.

**Pull request merged**
