### PR TITLE
doc cleanup prototype

### PR DESCRIPTION
**Pull request by ArnoStrouwen**
- preview cleanup CI taken from MuladdMacro.jl
- enable preview
- remove analytics

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Where would one see the preview?

**Comment by fredrikekre** [comment]
Documenter will post a commit status with the link. It only works on PRs from branches in the same repository, because otherwise the SSH key is not available (so it won't post any preview for this PR). Here is an example: https://github.com/fredrikekre/Literate.jl/pull/195 (open the commit status, click the link under `documenter/deploy` > `Details`).

**Comment by ChrisRackauckas** [comment]
I don't see that same preview link here?

**Comment by ArnoStrouwen** [comment]
As @fredrikekre said, no preview links from forks.

**Pull request merged**
