### PR TITLE
Mutable cache form

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
I think this is required to fix https://github.com/SciML/LinearSolve.jl/issues/302 . Otherwise there is no way to set some kind of "has been factorized". The reason for the functional immutable form was to be easier on the compiler, but I don't think that has worked out in the end. It has been a bit unergonomic to have to keep finding the latest cache, and in scenarios where it's kept longer (i.e. `init` the ODE solver) it will allocate just the same, while when it's in a more constrained context (`solve` in the ODE solver) the compiler will elide the allocation for both the mutable and immutable forms these days. Also, this puts LinearSolve more in line with the rest of the SciML interface libraries.

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
This is majorly breaking so it will be 2.0.

**Comment by fredrikekre** [comment]
> This is majorly breaking so it will be 2.0.

Can I request to change the default behavior of copying the matrix/vector if there will be a breaking release? :)

**Comment by ChrisRackauckas** [comment]
What's the requested change?

**Comment by fredrikekre** [comment]
To not copy by default.

**Comment by j-fu** [comment]
Hi, this seems to be an interesting improvement regarding usability of the API. I will try to test this with VoronoiFVM.jl, I should be able to find some time this week, would report back.

**Comment by ChrisRackauckas** [comment]
> To not copy by default, flipping these

Is there a way to do that and still solve the problem that two solves by default give the same answer? I'm not sure there is?

**Comment by fredrikekre** [comment]
Do you have an MWE for what you mean?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/LinearSolve.jl/issues/302 is something that for example I'm not sure would work.

**Comment by j-fu** [comment]
Seems to work for me, simplifies things big time! I one place I had a mutable struct which just wrapped a LinearCache to carry around...


But why make this immediately breaking ? IMHO it could be possible to keep the old API via `solve` and the new one via `solve!` . May be it could be deprecated and removed  later.

This also would prevent making packages using LinearSolve 1.0 and 
LinearSolve 2.0 incompatible.

**Comment by ChrisRackauckas** [comment]
I should/will go back and add deprecation paths, but it's much easier to test things by removing the syntax that shouldn't be used and then after everything works adding the deprecation paths back.

**Comment by ChrisRackauckas** [comment]
@fredrikekre if you think that's solvable, please open an issue and let's discuss what to do there. I don't plan to tag until the end of the week so this can get some more testing, and a few more necessary changes in.

**Comment by j-fu** [comment]
Checked for compatibility of the immutatable cache stuff - this works as well  :+1:

**Pull request merged**
