### PR TITLE
prototype reproducibility docs

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Is there any way we can give someone the manifest to download?

**Comment by fredrikekre** [comment]
Why not just commit `docs/Manifest.toml`?

**Comment by ChrisRackauckas** [comment]
Because then it doesn't update and it's not a good doc test.

**Comment by ArnoStrouwen** [comment]
If you don't want to commit the manifest, we can maybe copy it to assets in `make.jl` and then link it like:
https://github.com/SciML/LinearSolve.jl/tree/gh-pages/v1.19.0/assets
which will at least work for all the stable docs.

You can go further and for dev link things like:
https://github.com/SciML/LinearSolve.jl/tree/ceafea5e1291d6902c781abf43bc877cd6c16d42/dev/assets

**Comment by ChrisRackauckas** [comment]
I think putting it in the assets is a nice idea.

**Pull request merged**
